image: docker.fslab.de/lschau2s/debian-zfs-installer

stages:
  - build

build:
  stage: build
  only:
    changes:
      - build.sh
      - Dockerfile
      - install.py
      - files/**/*
  artifacts:
    paths:
      - debian-custom.iso
    expire_in: 2h
    expose_as: 'Live ISO'
  script:
    - ./build.sh
